server:
  port: 8087

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
      properties:
        hibernate:
          show_sql: true